// <auto-generated />
using BotanyExperts.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BotanyExperts.Migrations
{
    [DbContext(typeof(BotanyExpertsContext))]
    partial class BotanyExpertsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BotanyExperts.Models.Plant", b =>
                {
                    b.Property<int>("PlantId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CommonName");

                    b.Property<bool>("HasRoots");

                    b.Property<string>("ImgUrl");

                    b.Property<bool>("MakeFlowers");

                    b.Property<bool>("MakeSeeds");

                    b.Property<string>("ScientificName");

                    b.HasKey("PlantId");

                    b.ToTable("Plants");
                });
#pragma warning restore 612, 618
        }
    }
}
